# -*- coding: utf-8 -*-
"""house linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1562fq3QzplIHhKX7iFERbosYYoz-P7ty
"""

from google.colab import files
uploaded=files.upload()

!pip install pandas
import pandas as pd
d=pd.read_csv('Housing.csv')
d

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

furnishing_map={
    "unfurnished": 0,
    "semi-furnished": 1,
    "furnished": 2
}

d["furnishingstatus"]=d["furnishingstatus"].map(furnishing_map)

le=LabelEncoder()
cols = ["mainroad", "guestroom", "basement", "hotwaterheating", "airconditioning", "prefarea"]

for col in cols:
    d[col] = le.fit_transform(d[col])

d.isnull().sum()

d



x=d.drop("price", axis=1)
y=d["price"]

x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)
model=LinearRegression()
model.fit(x_train, y_train)
y_pred=model.predict(x_test)

MAE=mean_absolute_error(y_test, y_pred)
MSE=mean_squared_error(y_test, y_pred)
RMSE=np.sqrt(MSE)
R2=r2_score(y_test, y_pred)

plt.scatter(y_test, y_pred)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted")
plt.show()

coeff_df = pd.DataFrame(model.coef_, x.columns, columns=["Coefficient"])
coeff_df



X_1 = d[["area"]]
y = d["price"]

X_train, X_test, y_train, y_test = train_test_split(X_1, y, test_size=0.2, random_state=42)

model_simple = LinearRegression()
model_simple.fit(X_train, y_train)

y_pred_simple = model_simple.predict(X_test)


plt.scatter(X_test, y_test)
plt.plot(X_test, y_pred_simple)
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Regression Line")
plt.show()

plt.scatter(d["area"], d["price"])
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Area vs Price")
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(d.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

